# Generated by Django 5.0.4 on 2024-05-17 14:39

# import re

from django.conf import settings
from django.db import migrations

# from routedb.models import RasterMap
# from utils.s3 import s3_rename_object


def transfer_data(apps, schema_editor):
    # maps = RasterMap.objects.all()
    # for rmap in maps:
    #     old_name = rmap.image.name
    #     if re.match(r"[a-z]", old_name[5]) or re.match(r"[a-z]", old_name[7]):
    #         new_name = f"maps/{old_name[5:8].upper()}{old_name[8:]}"
    #         print(f"{old_name} -> {new_name}")
    #         s3_rename_object(settings.AWS_S3_BUCKET, old_name, new_name)
    #         rmap.image.name = new_name
    #         rmap.save()
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("routedb", "0020_route_is_private"),
    ]

    operations = [
        migrations.RunPython(transfer_data, migrations.RunPython.noop),
    ]