# Generated by Django 4.2.15 on 2024-09-19 08:57

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routedb", "0021_caseinsensitivestorage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.expressions.Case,
                        related_name="thumbsup",
                        to="routedb.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbsup_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "thumb Up",
                "verbose_name_plural": "thumbs up",
                "ordering": ["-creation_date"],
            },
        ),
    ]
