# Generated by Django 4.2.15 on 2024-09-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routedb", "0022_thumbup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbup",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbsup",
                to="routedb.route",
            ),
        ),
    ]
