# Generated by Django 4.2.15 on 2024-09-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routedb", "0024_usersettings_date_fetched_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thumbup",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "thumb up",
                "verbose_name_plural": "thumbs up",
            },
        ),
        migrations.AddField(
            model_name="usersettings",
            name="date_fetched_comments",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(max_length=1024)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="routedb.route",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["-creation_date"],
            },
        ),
    ]
